// NOTICE: This file was automatically generated by UCPP; do not edit this file manualy.
// UCPP Version 1.5; http://wiki.beyondunreal.com/wiki/UCPP
// #pragma ucpp include ../../UsUnit/macros.inc

/*******************************************************************************
    TEST_TimedTest
    This test does some timing tests.

    Written by: Michiel "El Muerte" Hendriks <elmuerte@drunksnipers.com>

    UsUnit Testing Framework
    Copyright (C) 2005, Michiel "El Muerte" Hendriks

    This program is free software; you can redistribute and/or modify
    it under the terms of the Lesser Open Unreal Mod License.
    <!-- $Id: TEST_TimedTest.uc,v 1.6 2005/09/22 13:59:29 elmuerte Exp $ -->
*******************************************************************************/

class TEST_TimedTest extends TestCase;

var float LastTime;

function run()
{
    LastTime = Level.TimeSeconds;
    SetTimer(10.0, false);
}

event Timer()
{
    // because of float signification it might not be 10.0
    check((Level.TimeSeconds - LastTime) > 9.99, "Time passed should be at least 10 seconds"$chr(3)$"d:\\dev\\ut2004\\ut2-code\\UsUnitExamples\\Classes\\TEST_TimedTest.uc"$"("$string(32)$")");
    done();
}

function byte getProgress() { return Checks/2*100; }

defaultproperties
{
    TestName="Timed Tests"
    TestDescription="This test does some timing tests."
}