// NOTICE: This file was automatically generated by UCPP; do not edit this file manualy.
// UCPP Version 1.0; http://wiki.beyondunreal.com/wiki/UCPP
// #ucpp include ../../UsUnit/macros.inc

/*******************************************************************************
    TEST_SimpleTests
    Example test case, performs some simple tests like basic math testing.

    Written by: Michiel "El Muerte" Hendriks <elmuerte@drunksnipers.com>

    UsUnit Testing Framework
    Copyright (C) 2005, Michiel "El Muerte" Hendriks

    This program is free software; you can redistribute and/or modify
    it under the terms of the Lesser Open Unreal Mod License.
    <!-- $Id: TEST_SimpleTests.uc,v 1.5 2005/06/28 09:45:05 elmuerte Exp $ -->
*******************************************************************************/

class TEST_SimpleTests extends TestCase;

function run()
{
    local array<string> dummy;
    check(1+1 == 2, "1+1 == 2"$chr(3)$"d:\\dev\\ut2004\\ut2-code\\UsUnitExamples\\Classes\\TEST_SimpleTests.uc"$"("$string(24)$")");
    check("CaseInsensitive" ~= "caseinsensitive", "\"CaseInsensitive\" ~= \"caseinsensitive\""$chr(3)$"d:\\dev\\ut2004\\ut2-code\\UsUnitExamples\\Classes\\TEST_SimpleTests.uc"$"("$string(25)$")");
    check(false, "false; will always fail"$chr(3)$"d:\\dev\\ut2004\\ut2-code\\UsUnitExamples\\Classes\\TEST_SimpleTests.uc"$"("$string(26)$")");
    check(split("one two three four five", " ", dummy) == 5, "\"one two three four five\" has 5 words"$chr(3)$"d:\\dev\\ut2004\\ut2-code\\UsUnitExamples\\Classes\\TEST_SimpleTests.uc"$"("$string(27)$")");
    check(split("one", " ", dummy) == 1, "\"one\" is 1 word"$chr(3)$"d:\\dev\\ut2004\\ut2-code\\UsUnitExamples\\Classes\\TEST_SimpleTests.uc"$"("$string(28)$")");
    check(round(1.5) == 2, "round(1.5) == 2"$chr(3)$"d:\\dev\\ut2004\\ut2-code\\UsUnitExamples\\Classes\\TEST_SimpleTests.uc"$"("$string(29)$")");
    check(int(1.5) == 1, "int(1.5) == 1"$chr(3)$"d:\\dev\\ut2004\\ut2-code\\UsUnitExamples\\Classes\\TEST_SimpleTests.uc"$"("$string(30)$")");
    done();
}

defaultproperties
{
    TestName="Simple Tests"
    TestDescription="Example test case, performs some simple tests basic math testing."
}